[2023-10-19T20:01:27.824+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_db_dag.fetch_changed_movies_ids scheduled__2023-10-19T20:00:25.430370+00:00 [queued]>
[2023-10-19T20:01:27.832+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_db_dag.fetch_changed_movies_ids scheduled__2023-10-19T20:00:25.430370+00:00 [queued]>
[2023-10-19T20:01:27.832+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-19T20:01:27.857+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_changed_movies_ids> on 2023-10-19 20:00:25.430370+00:00
[2023-10-19T20:01:27.867+0000] {standard_task_runner.py:57} INFO - Started process 14532 to run task
[2023-10-19T20:01:27.886+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_db_dag', 'fetch_changed_movies_ids', 'scheduled__2023-10-19T20:00:25.430370+00:00', '--job-id', '2117', '--raw', '--subdir', 'DAGS_FOLDER/test_movie_etl.py', '--cfg-path', '/tmp/tmp7qxcgxj8']
[2023-10-19T20:01:27.904+0000] {standard_task_runner.py:85} INFO - Job 2117: Subtask fetch_changed_movies_ids
[2023-10-19T20:01:27.971+0000] {task_command.py:416} INFO - Running <TaskInstance: postgres_db_dag.fetch_changed_movies_ids scheduled__2023-10-19T20:00:25.430370+00:00 [running]> on host 4b99fd46be77
[2023-10-19T20:01:28.055+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_db_dag' AIRFLOW_CTX_TASK_ID='fetch_changed_movies_ids' AIRFLOW_CTX_EXECUTION_DATE='2023-10-19T20:00:25.430370+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-19T20:00:25.430370+00:00'
[2023-10-19T20:01:28.066+0000] {base.py:73} INFO - Using connection ID 'postgres_db' for task execution.
[2023-10-19T20:01:28.079+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_movie_etl.py", line 31, in fetch_changed_movies_ids
    pg_conn = pg_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "films-db" to address: Name or service not known

[2023-10-19T20:01:28.096+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=postgres_db_dag, task_id=fetch_changed_movies_ids, execution_date=20231019T200025, start_date=20231019T200127, end_date=20231019T200128
[2023-10-19T20:01:28.112+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2117 for task fetch_changed_movies_ids (could not translate host name "films-db" to address: Name or service not known
; 14532)
[2023-10-19T20:01:28.137+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-19T20:01:28.158+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
