[2023-10-21T16:57:12.055+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Theatre_ETL.es_create_index scheduled__2023-10-21T16:56:09.417875+00:00 [queued]>
[2023-10-21T16:57:12.063+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Theatre_ETL.es_create_index scheduled__2023-10-21T16:56:09.417875+00:00 [queued]>
[2023-10-21T16:57:12.063+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-21T16:57:12.073+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): es_create_index> on 2023-10-21 16:56:09.417875+00:00
[2023-10-21T16:57:12.080+0000] {standard_task_runner.py:57} INFO - Started process 669 to run task
[2023-10-21T16:57:12.087+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Theatre_ETL', 'es_create_index', 'scheduled__2023-10-21T16:56:09.417875+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/test_movie_etl.py', '--cfg-path', '/tmp/tmp17maxe6k']
[2023-10-21T16:57:12.096+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask es_create_index
[2023-10-21T16:57:12.189+0000] {task_command.py:416} INFO - Running <TaskInstance: Theatre_ETL.es_create_index scheduled__2023-10-21T16:56:09.417875+00:00 [running]> on host 69e55cb2bf46
[2023-10-21T16:57:12.310+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Theatre_ETL' AIRFLOW_CTX_TASK_ID='es_create_index' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T16:56:09.417875+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-21T16:56:09.417875+00:00'
[2023-10-21T16:57:13.015+0000] {_transport.py:335} INFO - PUT http://elasticsearch:9200/movies [status:400 duration:0.063s]
[2023-10-21T16:57:13.020+0000] {test_movie_etl.py:196} ERROR - Ошибка: [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/04bawn7uSVaXA2IFLMj9UQ] already exists', 'index_uuid': '04bawn7uSVaXA2IFLMj9UQ', 'index': 'movies'}]
[2023-10-21T16:57:13.022+0000] {test_movie_etl.py:197} INFO - {'error': {'root_cause': [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/04bawn7uSVaXA2IFLMj9UQ] already exists', 'index_uuid': '04bawn7uSVaXA2IFLMj9UQ', 'index': 'movies'}], 'type': 'resource_already_exists_exception', 'reason': 'index [movies/04bawn7uSVaXA2IFLMj9UQ] already exists', 'index_uuid': '04bawn7uSVaXA2IFLMj9UQ', 'index': 'movies'}, 'status': 400}
[2023-10-21T16:57:13.023+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-21T16:57:13.048+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Theatre_ETL, task_id=es_create_index, execution_date=20231021T165609, start_date=20231021T165712, end_date=20231021T165713
[2023-10-21T16:57:13.094+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-21T16:57:13.133+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
