[2023-10-21T16:56:12.692+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Theatre_ETL.es_create_index scheduled__2023-10-21T16:55:09.417875+00:00 [queued]>
[2023-10-21T16:56:12.700+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Theatre_ETL.es_create_index scheduled__2023-10-21T16:55:09.417875+00:00 [queued]>
[2023-10-21T16:56:12.701+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-21T16:56:12.713+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): es_create_index> on 2023-10-21 16:55:09.417875+00:00
[2023-10-21T16:56:12.723+0000] {standard_task_runner.py:57} INFO - Started process 628 to run task
[2023-10-21T16:56:12.738+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Theatre_ETL', 'es_create_index', 'scheduled__2023-10-21T16:55:09.417875+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/test_movie_etl.py', '--cfg-path', '/tmp/tmp7bngi5km']
[2023-10-21T16:56:12.764+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask es_create_index
[2023-10-21T16:56:12.951+0000] {task_command.py:416} INFO - Running <TaskInstance: Theatre_ETL.es_create_index scheduled__2023-10-21T16:55:09.417875+00:00 [running]> on host 69e55cb2bf46
[2023-10-21T16:56:13.139+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Theatre_ETL' AIRFLOW_CTX_TASK_ID='es_create_index' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T16:55:09.417875+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-21T16:55:09.417875+00:00'
[2023-10-21T16:56:14.223+0000] {_transport.py:335} INFO - PUT http://elasticsearch:9200/movies [status:400 duration:0.037s]
[2023-10-21T16:56:14.226+0000] {test_movie_etl.py:196} ERROR - Ошибка: [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/04bawn7uSVaXA2IFLMj9UQ] already exists', 'index_uuid': '04bawn7uSVaXA2IFLMj9UQ', 'index': 'movies'}]
[2023-10-21T16:56:14.227+0000] {test_movie_etl.py:197} INFO - {'error': {'root_cause': [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/04bawn7uSVaXA2IFLMj9UQ] already exists', 'index_uuid': '04bawn7uSVaXA2IFLMj9UQ', 'index': 'movies'}], 'type': 'resource_already_exists_exception', 'reason': 'index [movies/04bawn7uSVaXA2IFLMj9UQ] already exists', 'index_uuid': '04bawn7uSVaXA2IFLMj9UQ', 'index': 'movies'}, 'status': 400}
[2023-10-21T16:56:14.229+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-21T16:56:14.267+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Theatre_ETL, task_id=es_create_index, execution_date=20231021T165509, start_date=20231021T165612, end_date=20231021T165614
[2023-10-21T16:56:14.326+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-21T16:56:14.392+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
