[2023-10-21T13:27:05.957+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cinema_ETL.es_create_index scheduled__2023-10-21T13:26:01.235699+00:00 [queued]>
[2023-10-21T13:27:05.965+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cinema_ETL.es_create_index scheduled__2023-10-21T13:26:01.235699+00:00 [queued]>
[2023-10-21T13:27:05.966+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-21T13:27:05.992+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): es_create_index> on 2023-10-21 13:26:01.235699+00:00
[2023-10-21T13:27:06.015+0000] {standard_task_runner.py:57} INFO - Started process 3248 to run task
[2023-10-21T13:27:06.024+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'cinema_ETL', 'es_create_index', 'scheduled__2023-10-21T13:26:01.235699+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/test_movie_etl.py', '--cfg-path', '/tmp/tmp9eh93xch']
[2023-10-21T13:27:06.043+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask es_create_index
[2023-10-21T13:27:06.217+0000] {task_command.py:416} INFO - Running <TaskInstance: cinema_ETL.es_create_index scheduled__2023-10-21T13:26:01.235699+00:00 [running]> on host 9f6b2b4cbb27
[2023-10-21T13:27:06.498+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cinema_ETL' AIRFLOW_CTX_TASK_ID='es_create_index' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T13:26:01.235699+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-21T13:26:01.235699+00:00'
[2023-10-21T13:27:07.902+0000] {_transport.py:335} INFO - PUT http://elasticsearch:9200/movies [status:400 duration:0.068s]
[2023-10-21T13:27:07.906+0000] {test_movie_etl.py:196} ERROR - Ошибка: [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/mZK33I7ySia1ExJA3_Hmcg] already exists', 'index_uuid': 'mZK33I7ySia1ExJA3_Hmcg', 'index': 'movies'}]
[2023-10-21T13:27:07.907+0000] {test_movie_etl.py:197} INFO - {'error': {'root_cause': [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/mZK33I7ySia1ExJA3_Hmcg] already exists', 'index_uuid': 'mZK33I7ySia1ExJA3_Hmcg', 'index': 'movies'}], 'type': 'resource_already_exists_exception', 'reason': 'index [movies/mZK33I7ySia1ExJA3_Hmcg] already exists', 'index_uuid': 'mZK33I7ySia1ExJA3_Hmcg', 'index': 'movies'}, 'status': 400}
[2023-10-21T13:27:07.907+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-21T13:27:07.960+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=cinema_ETL, task_id=es_create_index, execution_date=20231021T132601, start_date=20231021T132705, end_date=20231021T132707
[2023-10-21T13:27:08.010+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-21T13:27:08.080+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
