[2023-10-19T18:28:27.762+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_db_dag.fetch_changed_people_movies_ids scheduled__2023-10-19T18:27:24.252318+00:00 [queued]>
[2023-10-19T18:28:27.767+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_db_dag.fetch_changed_people_movies_ids scheduled__2023-10-19T18:27:24.252318+00:00 [queued]>
[2023-10-19T18:28:27.768+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-19T18:28:27.776+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_changed_people_movies_ids> on 2023-10-19 18:27:24.252318+00:00
[2023-10-19T18:28:27.783+0000] {standard_task_runner.py:57} INFO - Started process 11989 to run task
[2023-10-19T18:28:27.789+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_db_dag', 'fetch_changed_people_movies_ids', 'scheduled__2023-10-19T18:27:24.252318+00:00', '--job-id', '1745', '--raw', '--subdir', 'DAGS_FOLDER/test_movie_etl.py', '--cfg-path', '/tmp/tmpq8xmtn4u']
[2023-10-19T18:28:27.797+0000] {standard_task_runner.py:85} INFO - Job 1745: Subtask fetch_changed_people_movies_ids
[2023-10-19T18:28:27.884+0000] {task_command.py:416} INFO - Running <TaskInstance: postgres_db_dag.fetch_changed_people_movies_ids scheduled__2023-10-19T18:27:24.252318+00:00 [running]> on host 4b99fd46be77
[2023-10-19T18:28:27.964+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_db_dag' AIRFLOW_CTX_TASK_ID='fetch_changed_people_movies_ids' AIRFLOW_CTX_EXECUTION_DATE='2023-10-19T18:27:24.252318+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-19T18:27:24.252318+00:00'
[2023-10-19T18:28:27.977+0000] {base.py:73} INFO - Using connection ID 'postgres_db' for task execution.
[2023-10-19T18:28:28.022+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_movie_etl.py", line 67, in fetch_changed_people_movies_ids
    pg_conn = pg_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "films-db" to address: Name or service not known

[2023-10-19T18:28:28.043+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=postgres_db_dag, task_id=fetch_changed_people_movies_ids, execution_date=20231019T182724, start_date=20231019T182827, end_date=20231019T182828
[2023-10-19T18:28:28.054+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1745 for task fetch_changed_people_movies_ids (could not translate host name "films-db" to address: Name or service not known
; 11989)
[2023-10-19T18:28:28.080+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-19T18:28:28.115+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
