[2023-10-22T19:06:52.768+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Theatre_ETL.es_create_index manual__2023-10-22T19:06:47.999352+00:00 [queued]>
[2023-10-22T19:06:52.781+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Theatre_ETL.es_create_index manual__2023-10-22T19:06:47.999352+00:00 [queued]>
[2023-10-22T19:06:52.782+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-22T19:06:52.809+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): es_create_index> on 2023-10-22 19:06:47.999352+00:00
[2023-10-22T19:06:52.825+0000] {standard_task_runner.py:57} INFO - Started process 127 to run task
[2023-10-22T19:06:52.832+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Theatre_ETL', 'es_create_index', 'manual__2023-10-22T19:06:47.999352+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/test_movie_etl.py', '--cfg-path', '/tmp/tmpr3mncdr3']
[2023-10-22T19:06:52.853+0000] {standard_task_runner.py:85} INFO - Job 193: Subtask es_create_index
[2023-10-22T19:06:53.024+0000] {task_command.py:416} INFO - Running <TaskInstance: Theatre_ETL.es_create_index manual__2023-10-22T19:06:47.999352+00:00 [running]> on host cbf494a486db
[2023-10-22T19:06:53.212+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Theatre_ETL' AIRFLOW_CTX_TASK_ID='es_create_index' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T19:06:47.999352+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T19:06:47.999352+00:00'
[2023-10-22T19:06:55.084+0000] {_transport.py:335} INFO - PUT http://elasticsearch:9200/movies [status:400 duration:0.047s]
[2023-10-22T19:06:55.092+0000] {test_movie_etl.py:196} ERROR - Ошибка: [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/X24FFhT7Q623coBoaUAbsQ] already exists', 'index_uuid': 'X24FFhT7Q623coBoaUAbsQ', 'index': 'movies'}]
[2023-10-22T19:06:55.093+0000] {test_movie_etl.py:197} INFO - {'error': {'root_cause': [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/X24FFhT7Q623coBoaUAbsQ] already exists', 'index_uuid': 'X24FFhT7Q623coBoaUAbsQ', 'index': 'movies'}], 'type': 'resource_already_exists_exception', 'reason': 'index [movies/X24FFhT7Q623coBoaUAbsQ] already exists', 'index_uuid': 'X24FFhT7Q623coBoaUAbsQ', 'index': 'movies'}, 'status': 400}
[2023-10-22T19:06:55.093+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-22T19:06:55.130+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Theatre_ETL, task_id=es_create_index, execution_date=20231022T190647, start_date=20231022T190652, end_date=20231022T190655
[2023-10-22T19:06:55.189+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-22T19:06:55.242+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
