[2023-10-21T17:01:13.680+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Theatre_ETL.es_create_index scheduled__2023-10-21T17:00:09.417875+00:00 [queued]>
[2023-10-21T17:01:13.689+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Theatre_ETL.es_create_index scheduled__2023-10-21T17:00:09.417875+00:00 [queued]>
[2023-10-21T17:01:13.690+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-21T17:01:13.700+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): es_create_index> on 2023-10-21 17:00:09.417875+00:00
[2023-10-21T17:01:13.713+0000] {standard_task_runner.py:57} INFO - Started process 827 to run task
[2023-10-21T17:01:13.730+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Theatre_ETL', 'es_create_index', 'scheduled__2023-10-21T17:00:09.417875+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/test_movie_etl.py', '--cfg-path', '/tmp/tmp7vtry3v8']
[2023-10-21T17:01:13.736+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask es_create_index
[2023-10-21T17:01:13.806+0000] {task_command.py:416} INFO - Running <TaskInstance: Theatre_ETL.es_create_index scheduled__2023-10-21T17:00:09.417875+00:00 [running]> on host 69e55cb2bf46
[2023-10-21T17:01:13.908+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Theatre_ETL' AIRFLOW_CTX_TASK_ID='es_create_index' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T17:00:09.417875+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-21T17:00:09.417875+00:00'
[2023-10-21T17:01:14.227+0000] {_transport.py:335} INFO - PUT http://elasticsearch:9200/movies [status:400 duration:0.048s]
[2023-10-21T17:01:14.228+0000] {test_movie_etl.py:196} ERROR - Ошибка: [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/04bawn7uSVaXA2IFLMj9UQ] already exists', 'index_uuid': '04bawn7uSVaXA2IFLMj9UQ', 'index': 'movies'}]
[2023-10-21T17:01:14.228+0000] {test_movie_etl.py:197} INFO - {'error': {'root_cause': [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/04bawn7uSVaXA2IFLMj9UQ] already exists', 'index_uuid': '04bawn7uSVaXA2IFLMj9UQ', 'index': 'movies'}], 'type': 'resource_already_exists_exception', 'reason': 'index [movies/04bawn7uSVaXA2IFLMj9UQ] already exists', 'index_uuid': '04bawn7uSVaXA2IFLMj9UQ', 'index': 'movies'}, 'status': 400}
[2023-10-21T17:01:14.228+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-21T17:01:14.241+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Theatre_ETL, task_id=es_create_index, execution_date=20231021T170009, start_date=20231021T170113, end_date=20231021T170114
[2023-10-21T17:01:14.273+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-21T17:01:14.303+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
