[2023-10-20T06:39:34.913+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_db_dag.fetch_changed_people_movies_ids scheduled__2023-10-20T06:38:29.897000+00:00 [queued]>
[2023-10-20T06:39:34.931+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_db_dag.fetch_changed_people_movies_ids scheduled__2023-10-20T06:38:29.897000+00:00 [queued]>
[2023-10-20T06:39:34.931+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-20T06:39:34.951+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_changed_people_movies_ids> on 2023-10-20 06:38:29.897000+00:00
[2023-10-20T06:39:34.960+0000] {standard_task_runner.py:57} INFO - Started process 31938 to run task
[2023-10-20T06:39:34.965+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_db_dag', 'fetch_changed_people_movies_ids', 'scheduled__2023-10-20T06:38:29.897000+00:00', '--job-id', '4671', '--raw', '--subdir', 'DAGS_FOLDER/test_movie_etl.py', '--cfg-path', '/tmp/tmpnetpv1ks']
[2023-10-20T06:39:34.971+0000] {standard_task_runner.py:85} INFO - Job 4671: Subtask fetch_changed_people_movies_ids
[2023-10-20T06:39:35.070+0000] {task_command.py:416} INFO - Running <TaskInstance: postgres_db_dag.fetch_changed_people_movies_ids scheduled__2023-10-20T06:38:29.897000+00:00 [running]> on host 4b99fd46be77
[2023-10-20T06:39:35.165+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_db_dag' AIRFLOW_CTX_TASK_ID='fetch_changed_people_movies_ids' AIRFLOW_CTX_EXECUTION_DATE='2023-10-20T06:38:29.897000+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-20T06:38:29.897000+00:00'
[2023-10-20T06:39:35.180+0000] {base.py:73} INFO - Using connection ID 'postgres_db' for task execution.
[2023-10-20T06:39:35.227+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_movie_etl.py", line 67, in fetch_changed_people_movies_ids
    pg_conn = pg_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "films-db" to address: Name or service not known

[2023-10-20T06:39:35.240+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=postgres_db_dag, task_id=fetch_changed_people_movies_ids, execution_date=20231020T063829, start_date=20231020T063934, end_date=20231020T063935
[2023-10-20T06:39:35.314+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4671 for task fetch_changed_people_movies_ids (could not translate host name "films-db" to address: Name or service not known
; 31938)
[2023-10-20T06:39:35.340+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-20T06:39:35.377+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
