[2023-10-21T07:23:51.985+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_db_dag.fetch_changed_movies_ids scheduled__2023-10-21T07:22:46.456888+00:00 [queued]>
[2023-10-21T07:23:51.991+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_db_dag.fetch_changed_movies_ids scheduled__2023-10-21T07:22:46.456888+00:00 [queued]>
[2023-10-21T07:23:51.991+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-21T07:23:52.021+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_changed_movies_ids> on 2023-10-21 07:22:46.456888+00:00
[2023-10-21T07:23:52.029+0000] {standard_task_runner.py:57} INFO - Started process 72364 to run task
[2023-10-21T07:23:52.033+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_db_dag', 'fetch_changed_movies_ids', 'scheduled__2023-10-21T07:22:46.456888+00:00', '--job-id', '10605', '--raw', '--subdir', 'DAGS_FOLDER/test_movie_etl.py', '--cfg-path', '/tmp/tmp1d34v7i6']
[2023-10-21T07:23:52.036+0000] {standard_task_runner.py:85} INFO - Job 10605: Subtask fetch_changed_movies_ids
[2023-10-21T07:23:52.090+0000] {task_command.py:416} INFO - Running <TaskInstance: postgres_db_dag.fetch_changed_movies_ids scheduled__2023-10-21T07:22:46.456888+00:00 [running]> on host 4b99fd46be77
[2023-10-21T07:23:52.188+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_db_dag' AIRFLOW_CTX_TASK_ID='fetch_changed_movies_ids' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T07:22:46.456888+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-21T07:22:46.456888+00:00'
[2023-10-21T07:23:52.196+0000] {base.py:73} INFO - Using connection ID 'postgres_db' for task execution.
[2023-10-21T07:23:52.269+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_movie_etl.py", line 31, in fetch_changed_movies_ids
    pg_conn = pg_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "films-db" to address: Name or service not known

[2023-10-21T07:23:52.281+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=postgres_db_dag, task_id=fetch_changed_movies_ids, execution_date=20231021T072246, start_date=20231021T072351, end_date=20231021T072352
[2023-10-21T07:23:52.300+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10605 for task fetch_changed_movies_ids (could not translate host name "films-db" to address: Name or service not known
; 72364)
[2023-10-21T07:23:52.326+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-21T07:23:52.349+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
