[2023-10-21T13:35:04.717+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cinema_ETL.es_create_index scheduled__2023-10-21T13:34:01.235699+00:00 [queued]>
[2023-10-21T13:35:04.742+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cinema_ETL.es_create_index scheduled__2023-10-21T13:34:01.235699+00:00 [queued]>
[2023-10-21T13:35:04.743+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-21T13:35:04.776+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): es_create_index> on 2023-10-21 13:34:01.235699+00:00
[2023-10-21T13:35:04.789+0000] {standard_task_runner.py:57} INFO - Started process 3616 to run task
[2023-10-21T13:35:04.803+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'cinema_ETL', 'es_create_index', 'scheduled__2023-10-21T13:34:01.235699+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/test_movie_etl.py', '--cfg-path', '/tmp/tmp6ww_cw9x']
[2023-10-21T13:35:04.837+0000] {standard_task_runner.py:85} INFO - Job 109: Subtask es_create_index
[2023-10-21T13:35:04.982+0000] {task_command.py:416} INFO - Running <TaskInstance: cinema_ETL.es_create_index scheduled__2023-10-21T13:34:01.235699+00:00 [running]> on host 9f6b2b4cbb27
[2023-10-21T13:35:05.187+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cinema_ETL' AIRFLOW_CTX_TASK_ID='es_create_index' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T13:34:01.235699+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-21T13:34:01.235699+00:00'
[2023-10-21T13:35:05.860+0000] {_transport.py:335} INFO - PUT http://elasticsearch:9200/movies [status:400 duration:0.035s]
[2023-10-21T13:35:05.861+0000] {test_movie_etl.py:196} ERROR - Ошибка: [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/mZK33I7ySia1ExJA3_Hmcg] already exists', 'index_uuid': 'mZK33I7ySia1ExJA3_Hmcg', 'index': 'movies'}]
[2023-10-21T13:35:05.861+0000] {test_movie_etl.py:197} INFO - {'error': {'root_cause': [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/mZK33I7ySia1ExJA3_Hmcg] already exists', 'index_uuid': 'mZK33I7ySia1ExJA3_Hmcg', 'index': 'movies'}], 'type': 'resource_already_exists_exception', 'reason': 'index [movies/mZK33I7ySia1ExJA3_Hmcg] already exists', 'index_uuid': 'mZK33I7ySia1ExJA3_Hmcg', 'index': 'movies'}, 'status': 400}
[2023-10-21T13:35:05.862+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-21T13:35:05.872+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=cinema_ETL, task_id=es_create_index, execution_date=20231021T133401, start_date=20231021T133504, end_date=20231021T133505
[2023-10-21T13:35:05.919+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-21T13:35:05.961+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
